{
    "app_versions" => [
        0 => {
                         "notes" => "<p>Pre-rolls management</p>",
                  "shortversion" => "0.9",
                       "version" => "9",
                        "status" => 2,
            "minimum_os_version" => nil,
                     "mandatory" => false,
                     "timestamp" => 1326468169,
                       "appsize" => 396074,
                    "config_url" => "https://rink.hockeyapp.net/manage/apps/2505/app_versions/9",
                 "device_family" => nil,
                         "title" => "RTL XL"
        },
        1 => {
                         "notes" => "<p>The cover flow images are not the same for every image. This version specify a smaller zoom size to see if the cover flow looks better. Not quite that <span class=\"caps\">IMHO</span>.</p>",
                  "shortversion" => "0.8",
                       "version" => "8",
                        "status" => 2,
            "minimum_os_version" => nil,
                     "mandatory" => false,
                     "timestamp" => 1325597871,
                       "appsize" => 355744,
                    "config_url" => "https://rink.hockeyapp.net/manage/apps/2505/app_versions/8",
                 "device_family" => nil,
                         "title" => "RTL XL"
        },
        2 => {
                         "notes" => "<p>Fix dutch typo errors</p>",
                  "shortversion" => "0.7",
                       "version" => "7",
                        "status" => 2,
            "minimum_os_version" => nil,
                     "mandatory" => false,
                     "timestamp" => 1325597844,
                       "appsize" => 355758,
                    "config_url" => "https://rink.hockeyapp.net/manage/apps/2505/app_versions/7",
                 "device_family" => nil,
                         "title" => "RTL XL"
        },
        3 => {
                         "notes" => "<p>Add dutch and french languages<br />\nadd black background to lists and grids</p>",
                  "shortversion" => "0.6",
                       "version" => "6",
                        "status" => 2,
            "minimum_os_version" => nil,
                     "mandatory" => false,
                     "timestamp" => 1325597844,
                       "appsize" => 355724,
                    "config_url" => "https://rink.hockeyapp.net/manage/apps/2505/app_versions/6",
                 "device_family" => nil,
                         "title" => "RTL XL"
        },
        4 => {
                         "notes" => "<p>- Enhanced view for the tablets<br />\n- Connectivity checks on every request<br />\n- Fix a bug where 2 requests were sent at the same time.</p>",
                  "shortversion" => "0.5",
                       "version" => "5",
                        "status" => 2,
            "minimum_os_version" => nil,
                     "mandatory" => false,
                     "timestamp" => 1325597821,
                       "appsize" => 353289,
                    "config_url" => "https://rink.hockeyapp.net/manage/apps/2505/app_versions/5",
                 "device_family" => nil,
                         "title" => "RTL XL"
        },
        5 => {
                         "notes" => "<p>- Fix a visual text showed in the action bars</p>",
                  "shortversion" => "0.4",
                       "version" => "4",
                        "status" => 2,
            "minimum_os_version" => nil,
                     "mandatory" => false,
                     "timestamp" => 1325597809,
                       "appsize" => 352416,
                    "config_url" => "https://rink.hockeyapp.net/manage/apps/2505/app_versions/4",
                 "device_family" => nil,
                         "title" => "RTL XL"
        },
        6 => {
                         "notes" => "<p>- Check connectivity on start up only.<br />\n- Set loaders to show loading statuses.</p>",
                  "shortversion" => "0.3",
                       "version" => "3",
                        "status" => 2,
            "minimum_os_version" => nil,
                     "mandatory" => false,
                     "timestamp" => 1325597809,
                       "appsize" => 352373,
                    "config_url" => "https://rink.hockeyapp.net/manage/apps/2505/app_versions/3",
                 "device_family" => nil,
                         "title" => "RTL XL"
        },
        7 => {
                         "notes" => "<p>Test of update of the app</p>",
                  "shortversion" => "0.2",
                       "version" => "2",
                        "status" => 2,
            "minimum_os_version" => nil,
                     "mandatory" => false,
                     "timestamp" => 1325597802,
                       "appsize" => 349035,
                    "config_url" => "https://rink.hockeyapp.net/manage/apps/2505/app_versions/2",
                 "device_family" => nil,
                         "title" => "RTL XL"
        },
        8 => {
                         "notes" => "<p>Beta test version, including the search function.<br />\nTesting hockeyapp platform as well.</p>",
                  "shortversion" => "0.1",
                       "version" => "1",
                        "status" => 2,
            "minimum_os_version" => nil,
                     "mandatory" => false,
                     "timestamp" => 1325597802,
                       "appsize" => 349029,
                    "config_url" => "https://rink.hockeyapp.net/manage/apps/2505/app_versions/1",
                 "device_family" => nil,
                         "title" => "RTL XL"
        }
    ],
          "status" => "succss"
}