{
     "current_page" => 1,
           "status" => "success",
    "total_entries" => 10,
      "total_pages" => 1,
          "crashes" => [
        {
                     "user_string" => "",
                 "has_description" => false,
                      "os_version" => "2.2.1",
                              "id" => 5511786,
                  "bundle_version" => "2",
                 "crash_reason_id" => 135837,
                           "model" => "GT-S5830",
                  "app_version_id" => 2,
                  "contact_string" => "",
                             "oem" => "Samsung",
                      "updated_at" => "2011-12-15T20:06:53Z",
            "bundle_short_version" => "0.2",
                      "jail_break" => nil,
                      "created_at" => "2011-12-15T20:06:49Z",
                          "app_id" => 2505,
                         "has_log" => true
        },
        {
                     "user_string" => "",
                 "has_description" => false,
                      "os_version" => "2.2.1",
                              "id" => 5511818,
                  "bundle_version" => "2",
                 "crash_reason_id" => 135837,
                           "model" => "GT-S5830",
                  "app_version_id" => 2,
                  "contact_string" => "",
                             "oem" => "Samsung",
                      "updated_at" => "2011-12-15T20:07:12Z",
            "bundle_short_version" => "0.2",
                      "jail_break" => nil,
                      "created_at" => "2011-12-15T20:07:11Z",
                          "app_id" => 2505,
                         "has_log" => true
        },
        {
                     "user_string" => "",
                 "has_description" => false,
                      "os_version" => "2.3.6",
                              "id" => 5606753,
                  "bundle_version" => "2",
                 "crash_reason_id" => 137821,
                           "model" => "Nexus S",
                  "app_version_id" => 2,
                  "contact_string" => "",
                             "oem" => "samsung",
                      "updated_at" => "2011-12-16T09:14:47Z",
            "bundle_short_version" => "0.2",
                      "jail_break" => nil,
                      "created_at" => "2011-12-16T09:14:45Z",
                          "app_id" => 2505,
                         "has_log" => true
        },
        {
                     "user_string" => "",
                 "has_description" => false,
                      "os_version" => "2.3.6",
                              "id" => 5606754,
                  "bundle_version" => "2",
                 "crash_reason_id" => 137821,
                           "model" => "Nexus S",
                  "app_version_id" => 2,
                  "contact_string" => "",
                             "oem" => "samsung",
                      "updated_at" => "2011-12-16T09:14:47Z",
            "bundle_short_version" => "0.2",
                      "jail_break" => nil,
                      "created_at" => "2011-12-16T09:14:46Z",
                          "app_id" => 2505,
                         "has_log" => true
        },
        {
                     "user_string" => "",
                 "has_description" => false,
                      "os_version" => "2.3.6",
                              "id" => 5611176,
                  "bundle_version" => "2",
                 "crash_reason_id" => 137970,
                           "model" => "Nexus S",
                  "app_version_id" => 2,
                  "contact_string" => "",
                             "oem" => "samsung",
                      "updated_at" => "2011-12-16T10:39:06Z",
            "bundle_short_version" => "0.2",
                      "jail_break" => nil,
                      "created_at" => "2011-12-16T10:39:06Z",
                          "app_id" => 2505,
                         "has_log" => true
        },
        {
                     "user_string" => "",
                 "has_description" => false,
                      "os_version" => "2.3.7",
                              "id" => 8889748,
                  "bundle_version" => "7",
                 "crash_reason_id" => 179849,
                           "model" => "GT-I9000",
                  "app_version_id" => 7,
                  "contact_string" => "",
                             "oem" => "samsung",
                      "updated_at" => "2011-12-30T19:06:00Z",
            "bundle_short_version" => "0.7",
                      "jail_break" => nil,
                      "created_at" => "2011-12-30T19:05:57Z",
                          "app_id" => 2505,
                         "has_log" => true
        },
        {
                     "user_string" => "",
                 "has_description" => false,
                      "os_version" => "2.3.7",
                              "id" => 8890024,
                  "bundle_version" => "7",
                 "crash_reason_id" => 179849,
                           "model" => "GT-I9000",
                  "app_version_id" => 7,
                  "contact_string" => "",
                             "oem" => "samsung",
                      "updated_at" => "2011-12-30T19:07:11Z",
            "bundle_short_version" => "0.7",
                      "jail_break" => nil,
                      "created_at" => "2011-12-30T19:07:06Z",
                          "app_id" => 2505,
                         "has_log" => true
        },
        {
                     "user_string" => "",
                 "has_description" => false,
                      "os_version" => "2.2.1",
                              "id" => 9746147,
                  "bundle_version" => "8",
                 "crash_reason_id" => 183592,
                           "model" => "GT-S5830",
                  "app_version_id" => 8,
                  "contact_string" => "",
                             "oem" => "Samsung",
                      "updated_at" => "2012-01-02T18:58:21Z",
            "bundle_short_version" => "0.8",
                      "jail_break" => nil,
                      "created_at" => "2012-01-02T18:58:21Z",
                          "app_id" => 2505,
                         "has_log" => true
        },
        {
                     "user_string" => "",
                 "has_description" => false,
                      "os_version" => "2.2.1",
                              "id" => 9991007,
                  "bundle_version" => "8",
                 "crash_reason_id" => 184736,
                           "model" => "GT-S5830",
                  "app_version_id" => 8,
                  "contact_string" => "",
                             "oem" => "Samsung",
                      "updated_at" => "2012-01-03T15:01:59Z",
            "bundle_short_version" => "0.8",
                      "jail_break" => nil,
                      "created_at" => "2012-01-03T15:01:54Z",
                          "app_id" => 2505,
                         "has_log" => true
        },
        {
                     "user_string" => "",
                 "has_description" => false,
                      "os_version" => "2.3.5",
                              "id" => 12566355,
                  "bundle_version" => "8",
                 "crash_reason_id" => 200809,
                           "model" => "HTC Incredible S",
                  "app_version_id" => 8,
                  "contact_string" => "",
                             "oem" => "HTC",
                      "updated_at" => "2012-01-11T14:19:24Z",
            "bundle_short_version" => "0.8",
                      "jail_break" => nil,
                      "created_at" => "2012-01-11T14:19:22Z",
                          "app_id" => 2505,
                         "has_log" => true
        }
    ],
         "per_page" => 25
}